name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Reemplaza con tu rama principal si es diferente
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.5'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Install NPM dependencies
        run: npm ci
        working-directory: website  # Asegura que npm ci se ejecute en el directorio 'website'

      - name: Build Hugo site
        run: hugo --baseURL https://${REPO_OWNER}.github.io/${REPO_NAME} --minify
        working-directory: website  # Ejecuta Hugo dentro del directorio 'website'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/public  # Asegura que el directorio de salida de Hugo sea 'public'
          destination_dir: '.'  # Despliega el contenido directamente en la raíz de 'gh-pages'
